#开发环境配置文件
server:
  address: localhost
  port: 8091
spring:
  datasource:
    dynamic:
      primary: qdsrjcs #设置默认的数据源或者数据源组,默认值即为master。如果某个service或者mapper没有指定数据源，则使用默认的数据源
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        qdsrjcs:
          url: jdbc:mysql://10.2.11.114:3306/qdsrjcs?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
          username: root
          password: 147852369
        #          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        qdsbase:
          url: jdbc:mysql://10.2.11.114:3306/qds?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
          username: root
          password: 147852369
    #          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
    #数据库连接池
    hikari:
      read-only: false #连接只读数据库时配置为true，保证安全
      connection-test-query: SELECT 1
      idle-timeout: 15000  #空闲连接超时时间 idle-timeout+1秒不能超过max-lifetime，否则会置零，导致配置失效。
      validation-timeout: 3000
      max-lifetime: 30000 #设置数据库连接的生命周期，进行释放无用的数据库连接
      login-timeout: 5
      maximum-pool-size: 60 #连接池允许的最大连接数
      minimum-idle: 10   #设置最大空闲连接数
      connection-timeout: 30000 #等待连接池分配连接的最大时长，超过这个时长还没有可用连接则发生SQLException
  aop:
    auto: true
  #时间格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis
  redis:
    host: 10.2.11.114
    port: 6379
    database: 2
    password: greepushmsg123456
    timeout: 1000s  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
        #连接超时
        timeout: 3000
    cache:
      redis:
        time-to-live: -1 #毫秒
mybatis-plus: #从结果上看，mybatis-plus与mybatis的配置属性大部分相同，基本可以通用
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus控制台输出sql
    map-underscore-to-camel-case: true #开启驼峰式命名，默认值为true
    cache-enabled: false  #二级缓存，默认值为true
#swagger2
swagger2:
  enable: true
#第三方服务
third-service:
  common-post-url: http://127.0.0.1:8081/api/common-post
